padre(pam,bob).
padre(tom,bob).
padre(tom,liz).
padre(bob,ann).
padre(bob,pat).
padre(pat,jim).
mujer(pam).
mujer(pat).
mujer(ann).
mujer(liz).
hombre(tom).
hombre(bob).
hombre(jim).
diferente(X,Y).
hijo(Y,X):-padre(X,Y).
papa(X,Y):-padre(X,Y),hombre(X).
mama(X,Y):-padre(X,Y),mujer(X).
abuelo(X,Z):-padre(X,Y),padre(Y,Z).
hermana(X,Y):-padre(Z,X),padre(Z,Y),mujer(X),diferente(X,Y).
hermano(X,Y):-padre(Z,X),padre(Z,Y),hombre(X),diferente(X,Y).
tio(X,Y):-padre(Z,Y),hermano(X,Z).
tia(X,Y):-padre(Z,Y),hermana(X,Z).
descendencia(X,Z):-padre(X,Z).
descendencia(X,Z):-padre(X,Y),descendencia(Y,Z).